### ISSUE TITLE
HashiCorp Terraform Provider Development Program - Review

### ISSUE THREAD

**Issue by cgriggs01** [fgtdev/terraform-provider-fortios#1]
Hello Team

My name is Chris and I work on the Partner Alliances team here at HashiCorp. As part of the Terraform Provider Development Program. We will provider feedback on the provider for code best practices as well as requirement for ingress into the official Terraform Ecosystem. I've listed the items below. Please let me know if you have any questions about this feedback. 

- [x] Many of your resources READ and CREATE methods only return `nil`. As a best practice, the CREATE method of any Resource should at least return the results of it’s own READ method. In certain cases it may need to return the results of the UPDATE method, depending on if the CREATE method is capable of setting all possible configuration values. If for example the API call to create Resource only allows basic creation, the remaining configuration is applied via update, then CREATE should return UPDATE, and UPDATE should return READ. AWS Security Group Resource is an example of this; the CREATE only allows creating a Security Group with a name and description, and we must make other API calls to apply the rules. Thus, CREATE returns the results of UPDATE.  An UPDATE methods should always return the results of the READ method.

- [x] If a resource cannot be found(404) in the Read or Exists function, we should do a d.SetId("") to remove it from the statefile. You also wouldn't need to return an error then. Terraform will just treat it as a resource that never existed and try and create it.

 - [x] A call to d.Set() should always be error-checked on the fields data value being set is of type list or map. 

- [x] the following resource files have extensive amounts of code commented out in multiple functions. This functions should be implemented and unused commented code removed. 

```
resource_system_license_forticare.go
resource_system_license_vdom.go
resource_system_license_vm.go
resource_system_setting_dns.go
resource_system_setting_global.go
resource_system_setting_ntp.go
resource_log_fortianalyzer_setting.go
resource_log_syslog_setting.go
```

- [x] HashiCorp is now building Terraform providers using go1.11.5 and are adopting the use of Go Modules to manage the providers dependancies. 

- [x] There are a number of formatting changes that must be made in the the website documentation. I've created a small [PR #2](https://github.com/fgtdev/terraform-provider-fortios/pull/2) for these changes and will submit shortly.

**Comment by frankshen01** [comment]
Hi Chris, thanks a lot for the detailed reports and the PR, we have fixed all relevant code based on your suggestions and merged the pull request, we appreciate your detail.

**Comment by cgriggs01** [comment]
Hi Frank, thank you for the quick turn around.

We will make another review pass at the provider and see if there are any other items to address before we release the provider into the terraform-providers/ ecosystem.

**Comment by frankshen01** [comment]
Hi Chris, thanks for reviewing again. Your comments and suggestions are welcome. Look forward to the moment when we become a member of the terraform-providers/ ecosystem.

**Comment by cgriggs01** [comment]
Hi Frank,
I've got a few more items to address. Then we should be ready to release the provider under the terraform-providers/ Github organization. 

- [x] The semi-automated release process for providers uses  tf-release-bot to modify and update the CHANGELOG.md. This requires a specific format for the latest version number. You will need to change `1.0.0 (March 19, 2019)` --> `1.0.0 (Unreleased)`. The release date will then be added by the tf-release-bot.

- [ ] If a resource has an `Update` function it should have a corresponding acceptance tests. 

- [x] If a resource API does not allow a `Delete` operation, the `Delete` function should just return nil. In example the d.SetId("") shown [here](https://github.com/fgtdev/terraform-provider-fortios/blob/master/fortios/resource_log_syslog_setting.go#L95)

- [x] There are some unused and commented out variables in two resource files. "[portname](https://github.com/fgtdev/terraform-provider-fortios/blob/master/fortios/resource_networking_interface_port.go#L19)" and "[password](https://github.com/fgtdev/terraform-provider-fortios/blob/master/fortios/resource_system_admin_administrator.go#L170)"

This is the last of the feedback I have for you. Once completed we will start the migration and release of the provider!

**Comment by frankshen01** [comment]
Hi Chris, thank you so much for your careful review, which helps us a lot! 

>The semi-automated release process for providers uses tf-release-bot to modify and update the CHANGELOG.md. This requires a specific format for the latest version number. You will need to change 1.0.0 (March 19, 2019) --> 1.0.0 (Unreleased). The release date will then be added by the tf-release-bot.

Fixed

>If a resource API does not allow a Delete operation, the Delete function should just return nil. In example the d.SetId("") shown here

Fixed
>There are some unused and commented out variables in two resource files. "portname" and "password"

Fixed



> `If a resource has an Update function it should have a corresponding acceptance tests.`

We have some trouble here. There are 4 resources that have no corresponding accetance test, they are `system_license_forticare`, `system_license_vdom`, `system_license_vm` and `system_vdom_setting`.  After `system_license_forticare`, `system_license_vdom `or `system_license_vm` is configured, the device will restart immediately.  After `system_vdom_setting` is configured, the system will restart immediately too, and at the same time the device will switch to another mode of operation - VDOM mode, in which each resource needs to add a new vdom parameter to run properly.  All of this will cause other acceptance tests to stop running. We are somewhat confused about  the acceptance test for these four situations.  Could you please let me know if it is possible to ignore the acceptance test of these four resources? 

Thank you!

**Comment by cgriggs01** [comment]
Hey Frank, 

Thanks for address those so quickly. The untested resources will be alright, thanks for the explanation. 

We will start the provider code migration to the terraform-providers/ GitHub organization today and complete the release tomorrow. 

Please let me know if you have any questions or concerns. 

I'll close this issue now and follow up with you via email.
